palavras_tristes = [
    "desastre", "estragado","cansado", "estressado", "triste", "horrivel", "pesado", "chato", "puxado", "bad", "insuportavel",
    "deprimido", "sem_graca", "entediante", "exausto", "tenso", "caotico", "fraco", "baguncado", "lento",
    "pessimo", "dificil", "trabalhoso", "nublado", "parado", "morto", "confuso", "enjoado", "turbulento",
    "desanimado", "doido", "cinza", "nervoso", "corrido", "angustiante", "trabalhado", "tenso_demais",
    "bosta", "meio_ruim", "tristeza", "longoooo", "sofrido", "sem_paciencia", "complicado", "maluco",
    "derrotado", "zumbi", "desesperado", "cabisbaixo", "sem_vontade", "ladeira_abaixo", "saturado",
    "insuportavel", "chuvoso", "melancolico", "mal_humorado", "carregado", "azedo", "cheio", "doido",
    "insucesso", "preguicoso", "acumulado", "pesadao", "meio_tenso", "tristezinho", "problematico",
    "vazio", "mal", "sem_gas", "acabado", "to_podre", "meio_bosta", "revirado", "pesadinho", "enjoativo",
    "atolado", "sofrivel", "depressivo", "apatico", "acabando", "detonado", "meio_down", "sem_sorte",
    "ruim", "quebrado", "bagunca", "cheio_de_problema", "frustrante", "complicadinho", "tristeza_pura",
    "sem_tempo", "agoniado", "doido_demais", "sem_energia", "chateado", "pe_na_cova", "derrotinha",
    "insuportavelzinho", "morrendo", "sobrecarregado", "sem_graca_nenhuma", "malzao", "acabado_da_vida", "mortificado", "arrasado", "esgotado", "exaurido", "podre", "sozinho", "abandonado", "desolado",
    "desgostoso", "infeliz", "miseravel", "lamentavel", "doloroso", "sofrimento", "amargo", "amargurado",
    "irritado", "furioso", "puto", "com_raiva", "frustrado", "decepcionado", "desapontado", "ansioso",
    "preocupado", "tenso_novamente", "muito_ruim", "pessimo_dia", "dia_de_cao", "dia_dificil",
    "complicado_demais", "horripilante", "assustador", "medonho", "monotono", "repetitivo",
    "sem_esperanca", "sem_norte", "perdido", "sem_rumo", "falido", "no_fundo_do_poco", "na_merda",
    "no_lixo", "lixo", "porcaria", "droga", "que_merda", "terrivel", "desgastado"
]

palavras_felizes = [
    "otimo", "incrivel", "leve", "feliz", "tranquilo", "maravilhoso", "bom", "animado", "de_boa",
    "legal", "produtivo", "massa", "top", "divertido", "agradavel", "delicia", "suave", "bacana",
    "alegre", "positivo", "gostoso", "leveza", "paz", "perfeito", "show", "abencoado", "topzera",
    "ok", "animadinho", "maneiro", "sossegado", "satisfatorio", "sussa", "foi_tudo", "10_10",
    "tranquilao", "otimoo", "topissimo", "gostei", "deus_no_comando", "bom_d+", "felizao", "brabo",
    "sucesso", "legalzinho", "cheio_de_energia", "show_de_bola", "zen", "maravilha", "empolgado",
    "tranquilinho", "massa_demais", "sorridente", "okzinho", "good", "relax", "da_hora", "pra_frente",
    "motivado", "deus_abencoou", "good_vibes", "top_demais", "inspirado", "super_bom", "felicidade",
    "gratidao", "foi_lindo", "tudo_certo", "so_alegria", "suave_na_nave", "leve_leve", "otimasso",
    "deus_no_controle", "topster", "bao", "animadao", "tranquileba", "beleza", "maravilhindo",
    "empolgante", "delicioso", "alegria_pura", "vida_loka_boa", "abencoado_demais", "satisfatoriozinho",
    "chique", "deusebom", "megasuave", "okzao", "otimasso_mesmo", "felizona", "agradabilissimo",
    "lindao", "bencao", "supimpa", "100%", "pleno", "to_bem", "zenzao", "felicidade_pura", "sucesso_total",
    "radiante", "brilhante", "iluminado", "energizado", "eletrico", "vibrante", "extase", "em_extase",
    "euforico", "realizado", "satisfeito", "completo", "de_bem_com_a_vida", "nas_nuvens", "flutuando",
    "voando", "vitoria", "vitorioso", "campeao", "incrivelmente_bom", "sensacional", "fenomenal",
    "espetacular", "demais", "do_caralho", "foda", "muito_foda", "excelente", "magnifico", "glorioso",
    "dia_de_gloria", "dia_lindo", "dia_de_sol", "ceu_azul", "relaxado", "descansado", "renovado",
    "recarregado", "bateria_100", "grato", "muito_grato", "abencoado_por_deus", "coisa_boa", "que_bom",
    "tudo_otimo", "tudo_maravilhoso", "paz_interior", "de_boa_na_lagoa", "suave_total", "sem_problemas"
]
palavras_neutras = []
frases_coach_felizes = [
    "Sorria, o boleto pode esperar!",
    "Seja a pessoa que o Wi-Fi conecta automaticamente!",
    "Acordou feliz? Então já venceu metade do dia!",
    "Energia lá em cima, porque o chão já tá cheio de gente!",
    "Brilhe tanto que o recalque precisa de óculos escuros!",
    "Levanta, sacode a poeira e manda um pix pra você mesmo!",
    "Segue o baile, mas com glitter!",
    "Seja a vibe boa que seu chefe não entende!",
    "Nem todo herói usa capa, alguns só tomam café e resolvem tudo!",
    "Acordei radiante, e nem precisei de filtro!",
    "Gratidão demais até confunde o algoritmo do universo!",
    "O segredo é parecer ocupado e estar feliz mesmo assim!",
    "Sorte é quando o bom humor dá match com o café!",
    "Tô tão leve que se rir mais saio flutuando!",
    "Meta do dia: continuar incrível sem pedir desculpas!",
    "Quando o universo conspira a favor, eu conspiro junto!",
    "Manda energias boas, que hoje eu tô com Wi-Fi espiritual!",
    "Sorria! Dá bug na negatividade!",
    "Hoje tô tipo sol: aparecendo e esquentando geral!",
    "Felicidade em dia, planilha em atraso. Equilíbrio é tudo!",
    "A vida é curta, mas a playlist é longa. Bora curtir!",
    "Não sou coach, mas acredite: tá dando tudo certo!",
    "Café tomado, alma alinhada, e bora brilhar!",
    "Seja luz, mas se der, pisca também!",
    "Hoje tô radiante — deve ser o débito emocional compensando!",
    "Mais brilho, menos drama!",
    "Acordei com autoestima de story sem filtro!",
    "Sorria, você é o bug positivo no sistema da vida!",
    "A vibe tá tão boa que o estresse pediu folga!",
    "Deixe a preguiça pra quem não tem carisma!",
    "Seja o caos organizado que o universo respeita!",
    "Hoje eu tô tipo boleto pago: alívio puro!",
    "Quem disse que felicidade não paga conta nunca te viu produtivo sorrindo!",
    "Levanta a cabeça, arruma o cabelo e finge que é feriado!",
    "Tô tão motivado que até o espelho me aplaudiu!",
    "O universo me ama e o café confirmou!",
    "Sorte é pouco, tô com contrato vitalício com a alegria!",
    "Se o dia tá lindo, o problema é que eu sou demais!",
    "Hoje não tem tempo ruim — só meme bom!",
    "Brilhe, mas sem pedir permissão!",
    "Tô na vibe ‘não é sorte, é carisma’!",
    "Hoje acordei tão bem que o despertador pediu desculpa!",
    "Autocuidado é rir das próprias piadas e seguir pleno!",
    "Felicidade em dia e boletos sob controle emocional!",
    "Quando tudo dá certo, até o espelho sorri de volta!",
    "Seja grato, mas sem moderação!",
    "A positividade tá tão forte que nem a segunda-feira me segura!",
    "Hoje o plano é simples: ser incrível e tomar café!",
    "A vibe é boa, o humor tá pago e o sorriso é parcelado!",
    "Hoje tô tão zen que o trânsito virou trilha sonora!"
]
frases_coach_tristes = [
    "Levanta, guerreiro, o boleto não vai se pagar sozinho!",
    "A vida te deu limões? Faz uma caipirinha e segue!",
    "Chorar resolve nada, mas dá uma aliviada boa!",
    "Tá tudo desabando? Pelo menos o cabelo tá ok (talvez).",
    "Respira fundo e finge que tá tudo sob controle!",
    "Acordou triste? Bota um café pra resolver isso aí!",
    "A motivação fugiu, mas a ironia continua firme!",
    "Não tá fácil? Então vai difícil mesmo!",
    "O caos é temporário… eu acho.",
    "Se não der pra brilhar, pisca!",
    "Força, guerreiro! Só mais 86.400 segundos até amanhã!",
    "A vida é dura, mas o meme é mole!",
    "Nem sempre dá pra vencer, mas dá pra fingir no Instagram!",
    "Tudo passa. Pode ser um trator, mas passa!",
    "Se nada der certo, finge que é experimento social.",
    "Sorria! Vai confundir seus inimigos.",
    "Coragem: o pix emocional um dia cai!",
    "Tô cansado, mas sigo fingindo produtividade!",
    "Deus dá as batalhas mais aleatórias pros soldados mais confusos!",
    "Se for pra surtar, que seja com estilo!",
    "A vida é uma montanha-russa e eu tô sem cinto!",
    "Parece que deu ruim, mas pode piorar — calma!",
    "Vai dar certo! (Mentira, mas pensar ajuda.)",
    "Não desista, a vergonha alheia te motiva!",
    "O fundo do poço tem Wi-Fi, aproveita!",
    "Levanta a cabeça, senão a coroa cai — e é cara!",
    "Hoje tá ruim, amanhã melhora. Ou não. Mas tamo aí!",
    "Autoestima de planta esquecida, mas sigo regando!",
    "Não é preguiça, é modo economia de energia!",
    "A tristeza é só um bug do sistema — reinicia e vai!",
    "Pense positivo: pelo menos você não é um e-mail de spam!",
    "Caiu? Aproveita e tira um cochilo no chão!",
    "A vida é tipo boleto: vem, você ignora, e ela volta mais forte.",
    "Segunda chance? Eu só quero segunda-feira acabar!",
    "Você não tá perdido, só sem GPS emocional!",
    "Fracassar também é um tipo de experiência, né?",
    "Sofrer com classe é uma arte.",
    "A motivação foi tomar café e não voltou!",
    "Já deu tudo errado, agora relaxa e observa o caos!",
    "Tá tudo uma bagunça, mas pelo menos o meme tá bom.",
    "Força, guerreiro cansado — o Wi-Fi ainda tá funcionando!",
    "Se a vida te derrubar, aproveita e tira uma selfie criativa.",
    "Nada como um dia ruim atrás do outro pra criar resistência!",
    "O segredo da felicidade é fingir que tem um plano!",
    "Você é forte. Só tá com sono, fome e existindo errado.",
    "Chora, mas com dignidade e playlist boa!",
    "Nem terapia resolve, mas rir ajuda!",
    "Não deu certo? Tudo bem, você tentou (um pouco).",
    "A vida é um caos, mas o look tá impecável!",
    "Hoje a meta é sobreviver e, se der tempo, sorrir!"
]
frases_coach_neutras = [
    "Nem feliz, nem triste. Só atualizando o sistema.",
    "Hoje eu tô no modo economia de energia vital.",
    "Nem ruim, nem bom — só um capítulo de filler.",
    "A vibe é neutra, mas o café é forte.",
    "Tô igual planilha sem fórmula: existindo sem propósito.",
    "Hoje eu acordei no modo ‘tanto faz com fé’.",
    "Não tô bem, mas também não tô mal. Tô ‘tô’.",
    "Sigo em frente porque de ré gasta mais combustível.",
    "A motivação foi ali e disse que volta. Tô esperando.",
    "Hoje eu tô tipo nuvem: sem forma e passando.",
    "Nem caos, nem paz — só a segunda-feira normal.",
    "A vida não tá boa, mas tem memes, então tá ok.",
    "Modo automático ativado e sem previsão de desligar.",
    "Hoje tô funcional o suficiente pra não dar problema.",
    "Nem positivo, nem negativo — só carregando lentamente.",
    "A emoção de um copo de água morna.",
    "Não tô reclamando, mas também não tô aplaudindo.",
    "A vida segue. Devagar, mancando, mas segue.",
    "Hoje tô no modo 'não sei o que sinto, mas sinto algo'.",
    "Energia? Só se for elétrica.",
    "Nem caos nem calmaria, só fila de banco emocional.",
    "Hoje tô suave, tipo pão sem recheio.",
    "Nada demais acontecendo, e isso já é demais pra mim.",
    "O dia tá ok, e ok já é vitória.",
    "Nem ânimo, nem desânimo — apenas Wi-Fi intermitente.",
    "Tô vivo, e isso já é mais do que esperavam.",
    "Modo ‘tanto faz, mas com educação’.",
    "Hoje eu tô tipo emoji neutro: 🙂.",
    "Não espero nada e ainda assim me surpreendo.",
    "Nem ruim, nem bom — só uma terça-feira qualquer.",
    "A emoção tá no mesmo nível da bateria: 37%.",
    "Hoje tô só testando o recurso ‘existir’.",
    "Nada novo sob o sol, e tô de boa com isso.",
    "Tô indo… pra onde, não sei, mas tô indo.",
    "Hoje é um dia ‘ufa’, não um dia ‘oba’.",
    "Nem energia, nem preguiça — só observando a vida.",
    "Equilíbrio é aceitar o tédio com estilo.",
    "Hoje tô no modo espera — e sem pressa pra ser atendido.",
    "A vida tá tipo série longa: nem ruim o bastante pra desistir, nem boa o suficiente pra empolgar.",
    "Só existindo, igual planta de escritório.",
    "Hoje a meta é não surtar nem vibrar demais.",
    "Tô sereno, mas no limite do colapso — elegante, porém cansado.",
    "Nem empolgado nem desmotivado, só curioso pra ver no que dá.",
    "Hoje tô no modo ‘tô tentando, e isso já é esforço’.",
    "Equilíbrio perfeito entre o “meh” e o “ok”.",
    "Nem caos nem paz — só eu e meu café pensando na vida.",
    "A vida tá neutra, mas o humor continua afiado.",
    "Hoje eu tô tipo atualização de software: demorando, mas prometendo melhorias.",
    "Não tô animado, mas também não desisti — é sobre persistência passiva.",
    "Hoje tô no piloto automático, mas com GPS desligado.",
    "Nem emoção, nem drama — só o suspense da rotina."
]
